import BaseController from '../../../../Controllers/BaseController';
import Events from '../../../../Shared/Events';
import LayoutViewResource from './LayoutViewResource';
import ViewResource from './Individual/ViewResource';
import ViewResourceList from './List/ViewResourceList';
import ViewResourceListItem from './List/ViewResourceListItem';

/**
 * Controller for Resource views.
 */
class ResourceController extends BaseController
{
///////////////////////////////////////////////////////////////////////////////////////
// PRIVATE METHODS
///////////////////////////////////////////////////////////////////////////////////////
    /**
     * Initialize Radio.
     */
    _initializeRadio()
    {
        // Commands.
        this._rodanChannel.reply(Events.COMMAND__RESOURCE_ADD, aOptions => this._handleCommandResourceAdd(aOptions));
        this._rodanChannel.reply(Events.COMMAND__RESOURCE_DELETE, aOptions => this._handleCommandResourceDelete(aOptions));
        this._rodanChannel.reply(Events.COMMAND__RESOURCE_SAVE, aOptions => this._handleCommandResourceSave(aOptions));
        this._rodanChannel.reply(Events.COMMAND__RESOURCE_SHOWLAYOUTVIEW, options => this._handleCommandShowLayoutView(options));

        // Requests.
        this._rodanChannel.on(Events.EVENT__RESOURCES_SELECTED, aOptions => this._handleEventListSelected(aOptions));
        this._rodanChannel.on(Events.EVENT__RESOURCE_SELECTED, aOptions => this._handleEventItemSelected(aOptions));
   }
   
    /**
     * Handle show LayoutView.
     */
    _handleCommandShowLayoutView(options)
    {
        this._layoutView = options.layoutView;
    }

    /**
     * Handle list selection.
     */
    _handleEventListSelected(options)
    {
        this._layoutView = new LayoutViewResource({project: options.project});
        this._rodanChannel.request(Events.COMMAND__LAYOUTVIEW_SHOW, this._layoutView);
        this._layoutView.showList(new ViewResourceList({query: {project: options.project.id},
                                                        template: '#template-main_resource_list',
                                                        childView: ViewResourceListItem}));
    }

    /**
     * Handle item selection.
     */
    _handleEventItemSelected(options)
    {
        this._layoutView.showItem(new ViewResource(options));
    }

    /**
     * Handle command add Resource.
     */
    _handleCommandResourceAdd(options)
    {
        var collection = this._rodanChannel.request(Events.REQUEST__RESOURCE_COLLECTION);
        collection.create({project: options.project.get('url'), file: options.file}, {success: () => this._handleCallbackAddSuccess()});
    }

    /**
     * Handle command delete Resource.
     */
    _handleCommandResourceDelete(options)
    {
        if (options.resource.get('origin') !== null)
        {
            alert('Resources generated by Rodan cannot be deleted.'); 
        }
        else
        {
            var confirmation = confirm('Are you sure you want to delete this Resource?');
            if (confirmation)
            {
                try
                {
                    options.resource.destroy({success: () => this._handleCallbackDeleteSuccess()});
                }
                catch (aError)
                {
                    console.log('TODO - not sure why this error is happening; see https://github.com/ELVIS-Project/vis-client/issues/5');
                }
            }
        }
    }

    /**
     * Handle command save Resource.
     */
    _handleCommandResourceSave(options)
    {
        options.resource.save({resource_type: options.resource_type,
                                name: options.name,
                                description: options.description},
                               {patch: true, success: () => this._handleCallbackAddSuccess()});
    }

    /**
     * Handle delete success.
     */
    _handleCallbackDeleteSuccess()
    {
        var project = this._rodanChannel.request(Events.REQUEST__PROJECT_ACTIVE);
        this._rodanChannel.trigger(Events.EVENT__RESOURCES_SELECTED, {project: project});
    }

    /**
     * Handle add success.
     */
    _handleCallbackAddSuccess()
    {
        var project = this._rodanChannel.request(Events.REQUEST__PROJECT_ACTIVE);
        this._rodanChannel.request(Events.COMMAND__RESOURCES_LOAD, {query: {project: project.id}});
    }
}

export default ResourceController;